import { Vertical, Trend, Article } from './types';

// Initial Suggested Questions per vertical
export const SUGGESTED_QUESTIONS: Record<Vertical, string[]> = {
  [Vertical.Retail]: [
    "What are retailers doing right now to adapt stores for omnichannel shoppers?",
    "How are retailers using stores beyond just selling products?",
    "What’s changing in retail loyalty or membership strategies?",
    "How are retailers responding to margin pressure?"
  ],
  [Vertical.Sports]: [
    "What’s changing in how fans engage with sports outside of live games?",
    "How is technology reshaping athlete training and performance?",
    "What’s driving growth in women’s sports right now?",
    "How are leagues or teams experimenting with new revenue streams?"
  ],
  [Vertical.Beauty]: [
    "What’s changing in beauty around personalization and diagnostics?",
    "How are beauty brands using biotech or new ingredients?",
    "What’s driving the overlap between beauty and wellness?",
    "How are beauty brands responding to sustainability expectations?"
  ]
};

// Merged Data from Uploaded Files
export const MOCK_TRENDS: Trend[] = [
  // --- RETAIL (From Dataset) ---
  { id: "5367", vertical: Vertical.Retail, name: "Short-Run Co-Branded Pop-Up Retail Installations", summary: "Brands and retail partners open temporary, co-branded pop-up locations to launch limited product drops and curated experiences aimed at driving immediate foot traffic, email/social captures and PR." },
  { id: "5368", vertical: Vertical.Retail, name: "Computer Vision and AI Agent-Assisted In-Store Shopping", summary: "Stores deploy computer vision, virtual try-on tech, conversational AI agents and robotics to guide product selection and fitting, while cashierless or automated checkout systems speed transactions." },
  { id: "5369", vertical: Vertical.Retail, name: "Premium Prepared-Food Programs", summary: "Grocers, convenience chains and quick-service operators expand chef partnerships, higher-quality ready-to-eat meals and premium private-label items to capture additional dayparts." },
  { id: "5370", vertical: Vertical.Retail, name: "Targeted Store Expansion and Format Pilots", summary: "Well-funded operators accelerate new store openings and pilot distinct formats—flagship locations, experience-focused stores and takeout-only footprints—to secure local catchment." },
  { id: "5372", vertical: Vertical.Retail, name: "Geo-Triggered Commerce Enabled by Marketplaces", summary: "Marketplaces, real-time discovery tools and rapid last-mile logistics are integrated to trigger offers and fulfillment when consumers are nearby." },
  { id: "5373", vertical: Vertical.Retail, name: "Service-First Retail Stores", summary: "Retailers prioritize in-store services—repairs, clinics, click-and-collect, specialist consultations—and local programming to drive habitual visits and increase customer lifetime value." },
  { id: "5374", vertical: Vertical.Retail, name: "Retail-Integrated Resale and Curated Pre-Owned Assortments", summary: "Retailers adopt standardized refurbishment, grading and quality-control processes and curate pre-owned drops so second-hand inventory can be sold alongside new products." },
  { id: "5422", vertical: Vertical.Retail, name: "Airport Retail & Passenger Experience Elevation", summary: "Airports become experiential retail and service platforms (luxury flagships, meet & greet, autonomous delivery, immersive activations) to monetize dwell time." },
  { id: "5602", vertical: Vertical.Retail, name: "Background AI Agents for Revenue Ops", summary: "Background AI agents for on-site revenue operations and storefront automation that recommend or execute pricing, transfers, and next-best-actions at SKU-level." },
  { id: "5603", vertical: Vertical.Retail, name: "Conversational & Visual AI Shopping Advisors", summary: "Conversational and visual AI shopping advisors that close the loop from dialogue/vision to checkout across brand apps and platforms." },
  { id: "5604", vertical: Vertical.Retail, name: "Creator-Driven Resale, Drops & Circular Commerce", summary: "Creator-driven resale, scheduled drops and circular commerce that monetize scarcity, authenticated secondary markets and sustainability-driven resale programs." },
  { id: "5605", vertical: Vertical.Retail, name: "Autonomous Pricing/Promo Agents", summary: "Autonomous pricing/promo agents and AI‑native shopping channels collapse discovery and transaction into a single flow." },
  { id: "5609", vertical: Vertical.Retail, name: "Physical Retail Automation & Robotics", summary: "Customer-facing retail automation and robotics pilots that reconfigure in-store labor and last-mile delivery economics through autonomous units and robotic stores." },
  { id: "5610", vertical: Vertical.Retail, name: "Gamified, Compact Formats", summary: "Gamified compact formats use scarcity, randomness and collectible narratives (vending, blind‑boxes, drops) to drive frequent, low‑ticket purchases and social virality." },
  { id: "5611", vertical: Vertical.Retail, name: "Controlled Off‑Price & Brand‑Safe Secondary Channels", summary: "Brands create controlled off‑price and brand‑safe secondary channels—buyback, refurb and members‑only sales—to recover inventory value while protecting primary pricing." },
  { id: "5613", vertical: Vertical.Retail, name: "Retail Operational AI & Infrastructure", summary: "Retail operations are being rearchitected with AI, geospatial decisioning and modular services to cut cost‑to‑serve and enable omnichannel promises." },
  { id: "5614", vertical: Vertical.Retail, name: "Seamless Resale & Buyback Services", summary: "Seamless resale and buyback services normalize circular commerce by embedding trade‑ins, authenticated refurb and creator consignment into retail flows." },


  // --- SPORTS (From Dataset) ---
  { id: "5441", vertical: Vertical.Sports, name: "Team Kits as Culture, Music & Lifestyle Activation Vehicles", summary: "Clubs and rights-holders are converting kits into episodic, culturally framed lifestyle products that carry narrative, music and purpose beyond team identity." },
  { id: "5442", vertical: Vertical.Sports, name: "Rights-Led Sports Media Convergence", summary: "Rights holders convert single-asset deals into ongoing media stacks—venue IP, owned channels, and identity products—to create recurring fan commerce and first-party data." },
  { id: "5444", vertical: Vertical.Sports, name: "Boutique Fitness Formats Scaling via Franchising", summary: "Specialty training formats are being productized into franchisable studios, club integrations and eventized competitions to drive retention and unit economics." },
  { id: "5447", vertical: Vertical.Sports, name: "Athlete‑Driven Consumer Product Lines", summary: "Athletes’ equity is being translated into adjacent consumer categories and structured licensing to monetize fan trust across regions and categories." },
  { id: "5450", vertical: Vertical.Sports, name: "Sensor‑Verified Personalization", summary: "Sensor‑verified personalization and injury‑load management convert continuous sensor data into prescriptive coaching and injury‑risk alerts for athletes at all levels." },
  { id: "5454", vertical: Vertical.Sports, name: "AI‑Guided Home Strength Systems", summary: "AI‑guided home strength systems combine sensing, computer vision and adaptive resistance to deliver studio‑grade guidance and measurable progress at home." },
  { id: "5456", vertical: Vertical.Sports, name: "Fan Data, Personalization & Sponsorship Measurement", summary: "Rights holders and vendors investing in AI, personalization and measurement tools to personalize fan experiences and quantify sponsor ROI." },
  { id: "5458", vertical: Vertical.Sports, name: "Sensor + Recovery Convergence", summary: "Clubs integrate recovery and wellness modalities (cold plunges, red light, nervous‑system tech) as core offerings paired with apps to boost retention and ancillary revenue." },
  { id: "5459", vertical: Vertical.Sports, name: "Women’s Sport Participation & Player‑First Commercialization", summary: "Design, programming and commercial models are aligning to remove participation barriers in women’s sport and redirect economic value to players and communities." },
  { id: "5462", vertical: Vertical.Sports, name: "Standardized Franchise & Multi‑Brand Scaling", summary: "Standardized franchise and multi‑brand scaling leverages modular studio formats, franchisor tooling and proven unit economics to roll out rapidly and capital‑efficiently." },
  { id: "5556", vertical: Vertical.Sports, name: "Tech Partnerships Upgrading Live Sports Operations", summary: "Venue and rights-holder tech partnerships integrate payments, mobility, remote production and analytics to reduce costs, create sponsorable inventory, and improve fan experience." },
  { id: "5560", vertical: Vertical.Sports, name: "Eventized Fitness", summary: "Fitness packaged as ticketed, social entertainment—touring competitions, social sports venues and fitness cruises—monetized via sponsorships, F&B and ticketing." },
  { id: "5564", vertical: Vertical.Sports, name: "Human-Led, Tech-Enabled Coaching", summary: "Human coaching scaled with AI, sensors and AR to deliver measurable, cross-channel training while preserving human relationships." },
  { id: "5573", vertical: Vertical.Sports, name: "Modular & Multifunctional Sports Infrastructure", summary: "Flexible venue and equipment systems enable rapid reconfiguration, mixed-use programming and integrated data capture for year-round monetization." },
  { id: "5575", vertical: Vertical.Sports, name: "Adaptive & Inclusive Fitness Equipment", summary: "Adaptive and inclusive equipment/apparel designs broaden accessibility across institutions and everyday users." },

  // --- BEAUTY (From Dataset) ---
  { id: "5389", vertical: Vertical.Beauty, name: "Scented Experiences & Fragrance Extensions", summary: "Fragrance and scent experiences expand beyond bottles into wearables, accessories, spirits and place-based narratives to create multisensory brand touchpoints and repeatable rituals." },
  { id: "5391", vertical: Vertical.Beauty, name: "Immersive & Experiential Fragrance Retail", summary: "Theatrical IRL moments (pop-ups, destination stores, late-night drops) used as discovery funnels." },
  { id: "5392", vertical: Vertical.Beauty, name: "Tech & Science-Led Fragrance", summary: "Neuroscience, transparency and customization are reframing perfumery as measurable sensory science." },
  { id: "5393", vertical: Vertical.Beauty, name: "Discovery, Refill & Pre-Order Convenience", summary: "Sampler systems, refill fountains and pre-order pickup reduce friction and boost repurchase in fragrance retail." },
  { id: "5395", vertical: Vertical.Beauty, name: "Pleasure & Sexual Wellness in Personal Care", summary: "Products explicitly designed and marketed around sensual pleasure, texture and intimacy." },
  { id: "5396", vertical: Vertical.Beauty, name: "Provenance & Botanical Storytelling", summary: "Terroir-led narratives and traceable sourcing premiumize niche fragrances with authentic origin stories." },
  { id: "5397", vertical: Vertical.Beauty, name: "Fragrance IP & Collaboration Extensions", summary: "Fragrance becomes a storytelling platform—expanding through entertainment, character IP, and cultural collaborations." },
  { id: "5545", vertical: Vertical.Beauty, name: "Celebrity & Influencer-Led Fragrance Entrepreneurship", summary: "Creators and athletes leverage audience equity to launch scalable fragrance IP via DTC, licensing and retail exclusives." },
  { id: "5547", vertical: Vertical.Beauty, name: "Neuroscience & Data-Driven Fragrance", summary: "Suppliers and brands use neuroscience, large datasets and AI to design scents targeting emotional outcomes." },
  { id: "5551", vertical: Vertical.Beauty, name: "Novel Scent Formats & Delivery Mechanisms", summary: "Fragrance is expanding beyond bottles into edible, wearable, embedded and tech-integrated formats." },
  { id: "5552", vertical: Vertical.Beauty, name: "Conversion‑Linked Discovery Engines", summary: "Discovery engineered to directly drive attributable sales through sampling linked to redemption, AR try‑ons and AI matching." },
  { id: "5558", vertical: Vertical.Beauty, name: "One‑Step Performance", summary: "Multi‑function formulations that combine credible actives into one‑step hero SKUs, simplifying routines while delivering clinical outcomes." },
  { id: "5563", vertical: Vertical.Beauty, name: "Design‑Led Luxury & Experiential Objects", summary: "Transforming products and pop‑ups into collectible ritual objects and cultural moments to justify premium pricing." },
  { id: "5579", vertical: Vertical.Beauty, name: "Beauty Devices & Spa Automation", summary: "Clinic‑grade energy and delivery platforms miniaturized for at‑home use or integrated into retail clinics." },
  { id: "5581", vertical: Vertical.Beauty, name: "China’s Regional Beauty Acceleration", summary: "Policy, targeted finance and expos operate as a coordinated commercialization engine shortening time‑to‑market." },
  { id: "5583", vertical: Vertical.Beauty, name: "Salon & Spa Tech Professionalization", summary: "Adoption of enterprise tech, AI tools and credentialing to professionalize services and increase throughput." },
  { id: "5593", vertical: Vertical.Beauty, name: "K‑Beauty Globalization", summary: "K‑beauty R&D and manufacturing expertise exported via co‑development and localized formulation to enable region‑specific rollouts." },
  { id: "5594", vertical: Vertical.Beauty, name: "Beauty Devices & Clinic→Home Tech", summary: "Miniaturized energy tech, clearer regulatory pathways and consumer demand for clinic‑level results at home reduce adoption friction." },
  { id: "5595", vertical: Vertical.Beauty, name: "Hybrid Makeup‑Skincare / Skip‑Care Bases", summary: "Makeup bases that consolidate skincare actives and coverage into single clinically positioned SKUs." },
];

export const MOCK_ARTICLES: Article[] = [
  // --- RETAIL (From Dataset) ---
  { id: "7885", vertical: Vertical.Retail, trendIds: ["5367"], title: "Marc Jacobs and Nordstrom NYC: Fashion Meets Art", sourceUrl: "https://www.shopdropdaily.com/post/marc-jacobs-joy-pop-up-at-the-corner-nordstrom-nyc", snippet: "Marc Jacobs and Nordstrom have launched a pop-up called 'Marc Jacobs at The Corner', integrating fashion, art, and community engagement." },
  { id: "8052", vertical: Vertical.Retail, trendIds: ["5367"], title: "Carnaby Street Transformed: Barbour x FARM Rio", sourceUrl: "https://www.shopdropdaily.com/post/barbour-farm-rio-collection-takeover-carnaby-st-london", snippet: "Barbour collaborated with FARM Rio to transform its Carnaby Street store into a vibrant tropical escape with bold prints and lush foliage." },
  { id: "7185", vertical: Vertical.Retail, trendIds: ["5368"], title: "Grupo Boticário's AI Assistant Elevates Sales", sourceUrl: "https://abramark.com.br/destaques/grupo-boticario-revoluciona-e-commerce-com-ia-inspirada-em-uma-consultora-de-beleza-que-cria-rotinas-recomendacoes-personalizadas-e-ainda-ajuda-a-escolher-presentes/", snippet: "Grupo Boticário introduced an AI virtual assistant for their e-commerce app, offering personalized recommendations and support, boosting sales conversion by 46%." },
  { id: "5937", vertical: Vertical.Retail, trendIds: ["5368"], title: "Ralph Lauren Launches AI Styling Bot", sourceUrl: "https://www.businessoffashion.com/articles/technology/ralph-lauren-launches-ai-styling-bot-ask-ralph/", snippet: "Ralph Lauren introduced 'Ask Ralph,' an AI styling bot in their US app, offering real-time product recommendations and outfit guidance." },
  { id: "5875", vertical: Vertical.Retail, trendIds: ["5369"], title: "7-Eleven's Limit Over Series Surpasses 1 Million Sales", sourceUrl: "https://www.ddaily.co.kr/page/view/2025090913381178268", snippet: "7-Eleven introduced the 'Limit Over Series' of larger ready meals, exceeding 1 million sales with the launch of the 'Barbecue Beef Bento.'" },
  { id: "6499", vertical: Vertical.Retail, trendIds: ["5369", "5373"], title: "Eataly NYC Flatiron Engages Visitors", sourceUrl: "https://www.eataly.com/us_en/stores/nyc-flatiron/", snippet: "Eataly NYC Flatiron operates as a multi-level marketplace with grocery retail, various dining options, cooking classes, and events to boost visitor engagement." },
  { id: "7582", vertical: Vertical.Retail, trendIds: ["5370"], title: "Aldi UK’s £1.6 Billion Expansion", sourceUrl: "https://www.esmmagazine.com/retail/aldi-uk-commits-1-6-billion-to-ramp-up-store-expansion-296165", snippet: "Aldi UK is investing £1.6 billion to open 80 new stores over the next two years, targeting 1,500 total locations." },
  { id: "7240", vertical: Vertical.Retail, trendIds: ["5370"], title: "Casey’s Announces 500 New Stores", sourceUrl: "https://news.google.com/rss/articles/CBMi0AFBVV95cUxPQ2NiOF9mbGpZNzduWlkybTVBQlJZWl9QTEZBMVdMVWtrbzY1dUs3d29QMFE3Vlh4bnlyNi1JMzhXdnN5ZlctMXY2bWpRZmtyR00waElTLXRFeVNvZGpQX1lXVXN4bkxJRmFnVHBTSVMwVzVHVVJTZTQwMGk1b3dyQ0JjVTRVNHdVemd0QTJYODFVdjNnSnBzNkZMam9HdXhPand1UjI2U2lUa3ljVS0zOWppY0FWZW0tMkN5ZHc1TlZzRUlqeDhiQVFiZnRLY0xC?hl=en-US&gl=US&ceid=US%3Aen", snippet: "Casey's plans to open 500 new stores by September 2025, supported by record earnings, to boost market presence and service accessibility." },
  { id: "3424", vertical: Vertical.Retail, trendIds: ["5372"], title: "Fast Fashion Delivery: Flair's Lisbon Launch", sourceUrl: "https://www.nit.pt/compras/lojas-e-marcas/flair-nova-plataforma-nacional-junta-varias-marcas-de-moda-e-tem-entregas-em-2-horas", snippet: "Flair introduced a platform in Lisbon for fast, two-hour delivery of fashion items from ten partner brands." },
  { id: "6529", vertical: Vertical.Retail, trendIds: ["5373"], title: "REI Seattle Flagship Boosts Engagement", sourceUrl: "https://www.rei.com/stores/seattle.html", snippet: "REI Seattle Flagship sells outdoor gear and offers climbing, rentals, repairs, classes, and events to boost customer engagement and repeat visits." },
  { id: "6331", vertical: Vertical.Retail, trendIds: ["5374"], title: "Patagonia's Worn Wear Program", sourceUrl: "https://www.patagonia.com/worn-wear/", snippet: "Patagonia's Worn Wear program provides product care and repair services, hosts workshops, and supports local sustainability initiatives." },
  { id: "6412", vertical: Vertical.Retail, trendIds: ["5374"], title: "Amazon Renewed: Trustworthy Refurbished Options", sourceUrl: "https://www.amazon.com/renewed", snippet: "Amazon Renewed offers certified refurbished products with warranties, integrated into its marketplace alongside new items." },
  { id: "9126", vertical: Vertical.Retail, trendIds: ["5422"], title: "Transforming Changi Airport: Jewel Changi", sourceUrl: "https://www.changiairport.com/en/jewel.html", snippet: "Jewel Changi enhances Singapore Changi Airport with retail, dining, and attractions like the Rain Vortex, turning passenger dwell time into revenue." },
  { id: "11755", vertical: Vertical.Retail, trendIds: ["5603", "5605"], title: "Dialog's AI Agent Boosts Conversion", sourceUrl: "https://www.eu-startups.com/2025/11/with-300k-add-to-cart-events-paris-based-dialog-secures-e3-7-million-round-to-scale-its-ai-shopping-agent/", snippet: "Dialog launched an AI agent for e-commerce that triples conversion rates by providing personalized customer interactions." },
  { id: "10423", vertical: Vertical.Retail, trendIds: ["5604", "5614"], title: "eBay and Emma Chamberlain's Charity Auction", sourceUrl: "https://www.tubefilter.com/2025/11/06/ebay-emma-chamberlain-charity-sale-luxury-fashion/", snippet: "eBay collaborated with Emma Chamberlain to auction 100 personal wardrobe items for charity. This aligns with a wider trend of creator-driven resale." },
  { id: "10636", vertical: Vertical.Retail, trendIds: ["5610"], title: "Pop Mart's Times Square Flagship", sourceUrl: "https://retailboss.co/labubu-maker-pop-mart-launches-largest-u-s-flagship-times-square/", snippet: "Pop Mart signed a 10-year lease for a Times Square flagship, its largest U.S. retail move, set to open in 2026." },
  { id: "11464", vertical: Vertical.Retail, trendIds: ["5602", "5605"], title: "WOW AI - Sales Optimization", sourceUrl: "https://getwow.ai/en?utm_source=openai", snippet: "WOW AI uses real data to deliver accurate recommendations and smart strategies that boost conversions and increase sales." },
  { id: "5049", vertical: Vertical.Retail, trendIds: ["5609"], title: "Shenzhen's 6S Robot Store", sourceUrl: "https://news.google.com/rss/articles/CBMiVEFVX3lxTFAzUEY1X09SVmZsaVo5TE40SWk4SlhIUi11cDV1X1NQWXlPanFKbEVISVBMZ1NaTlFnSzRUMmgxZTExZF9HRUFCcW5YTjJfdlV5QkRGZg?oc=5", snippet: "Shenzhen's Galaxy World CoCo Park launched the 'World's First 6S Robot Store,' featuring robots for snacks, coffee, and service." },
  { id: "11549", vertical: Vertical.Retail, trendIds: ["5611"], title: "Beko Expands Appliance Refurbishment", sourceUrl: "http://www.trendhunter.com/innovation/reduce-refurbish-recycle", snippet: "Beko is expanding its program to refurbish and resell used appliances, enhancing availability through outlet shops and partners." },
  { id: "8943", vertical: Vertical.Retail, trendIds: ["5613"], title: "Milkyway - Local Delivery App", sourceUrl: "https://www.milkywaydelivery.com", snippet: "A free Shopify app that unifies local delivery, doorstep returns, live tracking, and parcel protection for stores across the U.S." },

  // --- SPORTS (From Dataset) ---
  { id: "9401", vertical: Vertical.Sports, trendIds: ["5441"], title: "Lululemon and Fanatics Expand NHL Merchandise", sourceUrl: "https://www.foxbusiness.com/sports/nhl-expands-lululemon-partnership-include-all-32-teams-upcoming-2025-26-season", snippet: "Lululemon and Fanatics are expanding their NHL merchandise line to include all 32 teams for the 2025–26 season, available online and in various retail locations." },
  { id: "7036", vertical: Vertical.Sports, trendIds: ["5441"], title: "Louis Vuitton Partners with Real Madrid Women’s Team", sourceUrl: "https://hypebae.com/2025/9/louis-vuitton-real-madrid-team-collaboration-formal-wear-release-date", snippet: "Louis Vuitton is collaborating with the Real Madrid women's football team to create exclusive Formal Wear and Travel Wear, including apparel, footwear, and accessories." },
  { id: "3509", vertical: Vertical.Sports, trendIds: ["5441", "5459"], title: "Skims Expands in Sports: Official Partner of League One Volleyball", sourceUrl: "https://athletechnews.com/kim-kardashians-skims-teams-with-lovb-as-loungewear-partner/", snippet: "Skims partners with League One Volleyball to provide official loungewear, integating into community events and digital platforms, highlighting female athletes." },
  { id: "9375", vertical: Vertical.Sports, trendIds: ["5441", "5442"], title: "Spotify and FC Barcelona Extend Sponsorship", sourceUrl: "https://sportsmintmedia.com/fc-barcelona-and-spotify-strengthen-global-ties-with-extended-sponsorship-alliance/", snippet: "FC Barcelona and Spotify extended their sponsorship until 2030... Naming rights for Spotify Camp Nou are extended to 2034, including structured payments." },
  { id: "9439", vertical: Vertical.Sports, trendIds: ["5442"], title: "Whoopi Goldberg and Jungo TV Launch Global Women's Sports Network", sourceUrl: "https://www.awsn.tv/about", snippet: "All Women’s Sports Network (AWSN) is a global 24/7 channel broadcasting women’s sports, covering major leagues like UEFA and WTA across 65 countries." },
  { id: "4906", vertical: Vertical.Sports, trendIds: ["5442", "5462"], title: "Pickleball's Evolution: Transforming Entertainment Hubs", sourceUrl: "https://athletechnews.com/pickleball-next-chapter-more-than-courts/", snippet: "Brands like The Pickle Pad and Chicken N Pickle create social venues combining dining, high-end coffee bars, and games to drive all-day dwell time." },
  { id: "1548", vertical: Vertical.Sports, trendIds: ["5462"], title: "PickleRage Aims for Nationwide Expansion", sourceUrl: "https://athletechnews.com/picklerage-inks-new-franchise-deals-across-us/", snippet: "PickleRage is expanding its indoor pickleball franchise with plans for over 500 locations nationwide in five years. Recently signed five new franchises." },
  { id: "3864", vertical: Vertical.Sports, trendIds: ["5462"], title: "JetSet Pilates Expands Globally", sourceUrl: "https://athletechnews.com/jetset-pilates-targets-200-territories-as-reformer-craze-builds/", snippet: "JetSet Pilates is opening 16 new studios in early 2025... targeting luxury areas. Since 2022, they've sold over 200 franchises." },
  { id: "5011", vertical: Vertical.Sports, trendIds: ["5447"], title: "Stanley 1913 Partners with Caitlin Clark", sourceUrl: "https://athletechnews.com/stanley-1913-partners-with-caitlin-clark-on-hydration-collection/", snippet: "Stanley 1913 is launching a signature hydration line with Caitlin Clark on September 3, featuring the Quencher ProTour Tumbler." },
  { id: "5949", vertical: Vertical.Sports, trendIds: ["5447"], title: "Vuori Expands Ambassador Program with Jared Goff", sourceUrl: "https://athletechnews.com/vuori-leans-into-athlete-partnerships-in-performance-wear-pivot/", snippet: "Vuori is expanding its athlete ambassador program with NFL quarterback Jared Goff... Supported by an $825 million funding round." },
  { id: "4917", vertical: Vertical.Sports, trendIds: ["5450"], title: "Virtuagym's Max AI Coach", sourceUrl: "https://athletechnews.com/virtuagym-launches-ai-fitness-coaching-tool-for-gyms-trainers/", snippet: "Virtuagym introduced Max AI Coach, an AI tool for creating quick, personalized workout plans using a large exercise database and trainer inputs." },
  { id: "2248", vertical: Vertical.Sports, trendIds: ["5450"], title: "Theo Health's Smart Alpha Shorts", sourceUrl: "https://athletechnews.com/theo-health-raises-1-2m-for-smart-shorts-that-take-training-to-the-next-level/", snippet: "Theo Health introduced Theo Alpha Shorts, smart activewear with movement-tracking technology... aims at providing real-time training insights." },
  { id: "1488", vertical: Vertical.Sports, trendIds: ["5454"], title: "AI-Powered Home Gym Revolutionizes Workouts", sourceUrl: "https://newatlas.com/fitness/aeke-k1-ai-coach-home-gym/", snippet: "The Aeke K1 home gym system offers an AI coach for personalized workouts, featuring a 43-inch 4K touchscreen and a powerful 750W motor." },
  { id: "9667", vertical: Vertical.Sports, trendIds: ["5454"], title: "AI-Driven Smart Home Gym Revolutionizes Personalized Fitness", sourceUrl: "https://www.tonal.com/", snippet: "Tonal offers a wall-mounted smart home gym with AI-driven resistance and sensors, delivering personalized workouts and real-time guidance." },
  { id: "9355", vertical: Vertical.Sports, trendIds: ["5456"], title: "Genius Sports Boosts Fan Insights", sourceUrl: "https://www.sportspro.com/news/genius-sports-innovation-lab-fan-data-sponsorship-september-2025/", snippet: "Genius Sports acquired Sports Innovation Lab to enhance fan data and sponsorship insights, integrating its research tools into Genius's media products." },
  { id: "1464", vertical: Vertical.Sports, trendIds: ["5458"], title: "Life Time Unveils Arden Hills Transformation", sourceUrl: "https://athletechnews.com/life-time-revives-former-arden-hills-club-with-eighth-california-location/", snippet: "Life Time has launched its eighth California location... nearly 80,000 square feet of upgraded fitness facilities, an outdoor beach club, and a Kids Academy." },
  { id: "2997", vertical: Vertical.Sports, trendIds: ["5458"], title: "Nervous System Recovery Tech Gains Momentum", sourceUrl: "https://athletechnews.com/shiftwaves-recovery-tech-turns-heads-at-the-atn-summit/", snippet: "Shiftwave's nervous system recovery technology... requires no additional staffing or space, is now implemented in resorts and wellness centers." },
  { id: "4938", vertical: Vertical.Sports, trendIds: ["5459", "5575"], title: "ASICS Launches Inclusive PE Uniform", sourceUrl: "https://www.trendwatching.com/innovations/a-reimagined-pe-kit-by-asics-responds-to-girls-dropping-out-of-sports", snippet: "ASICS launched the Undropped Kit, a PE uniform designed with Inclusive Sportswear and Mind, to address discomfort with traditional gym attire." },
  { id: "11494", vertical: Vertical.Sports, trendIds: ["5556"], title: "CHEQ - in-venue mobile ordering", sourceUrl: "https://www.cheqplease.com/pepsi", snippet: "CHEQ delivers mobile ordering... technology that powers friction-free purchases at stadiums... Reported results include a 28% lift in average ticket size." },
  { id: "10599", vertical: Vertical.Sports, trendIds: ["5556"], title: "OZ Sports - Smart stadium infrastructure", sourceUrl: "https://oz.com/", snippet: "OZ Sports builds AI-driven stadium infrastructure that delivers high-end, multi-camera 4K broadcasts with no on-site crew." },
  { id: "11989", vertical: Vertical.Sports, trendIds: ["5560"], title: "ATHX Games and Adidas Ink Global Deal", sourceUrl: "https://athletechnews.com/athx-games-global-expansion-adidas-partnership/", snippet: "ATHX Games partners with Adidas for a four-year global deal, launching a European tour in 2026 with fitness events and expanding its affiliate gym network." },
  { id: "12007", vertical: Vertical.Sports, trendIds: ["5560"], title: "Hyrox Launches Adult-Only Fitness Cruise", sourceUrl: "https://athletechnews.com/hyrox-fitness-cruise-vacation-experiences/", snippet: "Hyrox is launching the Hyrox Cruise, its first adult-only fitness cruise from October 21-25, 2026, starting in Palma de Mallorca." },
  { id: "12065", vertical: Vertical.Sports, trendIds: ["5573"], title: "Birmingham City FC Unveils 62,000-Seat Stadium", sourceUrl: "https://creapills.com/birmingham-nouveau-stade-football-heatherwick-manica-2030-20251124", snippet: "Birmingham City Football Club plans a 62,000-seat stadium with a retractable roof and removable pitch... part of the Birmingham Sports Quarter." },
  { id: "12083", vertical: Vertical.Sports, trendIds: ["5573"], title: "TRX Studio Line Offers Adaptable Solutions", sourceUrl: "https://athletechnews.com/trx-redefines-functional-training-for-the-next-era-of-fitness/", snippet: "TRX's Studio Line now includes anchored and freestanding solutions, enhancing gym flexibility and efficiency." },
  { id: "12160", vertical: Vertical.Sports, trendIds: ["5575"], title: "Adaptive Fitness: Life Fitness and Harper's College", sourceUrl: "https://athletechnews.com/life-fitness-hammer-strength-universal-cable-wheelchair-accessible/", snippet: "Life Fitness / Hammer Strength introduced the Universal Cable, a dual-adjustable pulley system designed for all users, including those in wheelchairs." },
  { id: "12179", vertical: Vertical.Sports, trendIds: ["5575"], title: "Motorized Core Trainer ZeroWheel", sourceUrl: "https://athletechnews.com/how-zerowheel-reinvented-core-training/", snippet: "ZeroWheel offers a motorized core training device that adjusts resistance for diverse fitness levels, from rehab clients to athletes." },
  { id: "12009", vertical: Vertical.Sports, trendIds: ["5564"], title: "AI Boosts Efficiency for Personal Trainers", sourceUrl: "https://athletechnews.com/personal-trainers-using-ai-but-not-blindly-embracing-it-issa-report/", snippet: "The ISSA report highlights that 52% of personal trainers use AI for backend tasks... fitness market projected to grow from $16.9 billion in 2025." },
  { id: "11996", vertical: Vertical.Sports, trendIds: ["5576"], title: "Apple Fitness+ Expands Globally", sourceUrl: "https://athletechnews.com/apple-fitness-plus-makes-its-biggest-global-push-yet/", snippet: "Apple Fitness+ is expanding to 28 new markets, adding dubbed content in several languages and a K-Pop genre." },
  { id: "12032", vertical: Vertical.Sports, trendIds: ["5580"], title: "Mindbody Launches Integrated Payment Platform", sourceUrl: "https://athletechnews.com/the-invisible-edge-how-mindbody-payments-powers-loyalty-retention-and-revenue/", snippet: "Mindbody introduced an integrated payment platform for fitness and wellness businesses, emphasizing contactless payments and digital wallets." },
  { id: "12200", vertical: Vertical.Sports, trendIds: ["5462", "5573"], title: "Social Padel Clubs and Artisanal Coffee Culture", sourceUrl: "https://athletechnews.com/the-rise-of-social-sports-clubs-padel-pickleball-and-premium-coffee/", snippet: "New multi-use sports venues are prioritizing artisanal coffee and cafe spaces to foster community, making 'sporting social clubs' a high-growth revenue segment." },

  // --- BEAUTY (From Dataset) ---
  { id: "9501", vertical: Vertical.Beauty, trendIds: ["5389"], title: "Aroma Wearable Tech Launch", sourceUrl: "https://www.fragrantica.com", snippet: "New wearable jewelry released that releases periodic bursts of signature scents to maintain personal fragrance levels throughout the day." },
  { id: "9502", vertical: Vertical.Beauty, trendIds: ["5392"], title: "Neuroscience-Backed Perfume Research", sourceUrl: "https://www.beautytech.com", snippet: "A major fragrance house uses brainwave tracking to identify which scent notes correlate most highly with stress reduction and focus." },
  { id: "9503", vertical: Vertical.Beauty, trendIds: ["5558"], title: "The Rise of One-Step Serums", sourceUrl: "https://www.skincareexpert.com", snippet: "Brands are consolidating 5-step routines into single 'hero' serums containing stabilized Vitamin C, Retinol, and Peptides." },
  { id: "9600", vertical: Vertical.Beauty, trendIds: ["5563"], title: "Cafe-Integrated Beauty Concept Stores", sourceUrl: "https://www.beautytech.com/cafe-retail-beauty-overlap", snippet: "Beauty retailers are launching 'wellness cafes' inside clinics, serving mood-boosting coffee and beverages alongside aesthetic treatments." },
];
