
import React from 'react';

interface DeterministicModalProps {
    isOpen: boolean;
    onClose: () => void;
}

export const DeterministicModal: React.FC<DeterministicModalProps> = ({ isOpen, onClose }) => {
    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-[250] flex items-center justify-center p-4">
            <div className="absolute inset-0 bg-stone-900/40 backdrop-blur-sm" onClick={onClose} />
            <div className="relative w-full max-w-2xl bg-white rounded-3xl shadow-2xl overflow-hidden animate-fade-in-up border border-stone-200 flex flex-col max-h-[90vh]">
                <div className="p-6 border-b border-stone-100 flex justify-between items-center bg-stone-50 shrink-0">
                    <div className="flex items-center space-x-3">
                        <div className="bg-fodda-accent/10 p-2 rounded-lg">
                            <svg className="w-5 h-5 text-fodda-accent" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" /></svg>
                        </div>
                        <h3 className="font-serif text-xl font-bold text-stone-900">Deterministic Mode</h3>
                    </div>
                    <button onClick={onClose} className="p-2 text-stone-400 hover:text-stone-900 transition-colors">
                        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>
                    </button>
                </div>

                <div className="p-8 space-y-8 overflow-y-auto text-stone-600 leading-relaxed text-sm scrollbar-hide">
                    <section>
                        <h4 className="text-[10px] font-bold text-stone-400 uppercase tracking-[0.2em] mb-4">Concept: Grounded Retrieval</h4>
                        <p>
                            Deterministic Mode ensures that every response generated by the AI is strictly grounded in the knowledge graph. If the required information is not present in the graph, the system will not "hallucinate" or generate synthetic facts.
                        </p>
                    </section>

                    <section className="pt-6 border-t border-stone-100">
                        <h4 className="text-[10px] font-bold text-stone-400 uppercase tracking-[0.2em] mb-4">Technical Safeguards</h4>
                        <ul className="space-y-4">
                            <li className="flex gap-3">
                                <div className="w-1.5 h-1.5 rounded-full bg-fodda-accent mt-1.5 shrink-0" />
                                <div>
                                    <span className="font-bold text-stone-900">NO_MATCH Fallback</span>
                                    <p className="text-xs text-stone-500 mt-0.5">When graph retrieval returns zero-confidence matches, the API returns a structured <code className="bg-stone-100 px-1 py-0.5 rounded text-stone-800">NO_MATCH</code> code.</p>
                                </div>
                            </li>
                            <li className="flex gap-3">
                                <div className="w-1.5 h-1.5 rounded-full bg-fodda-accent mt-1.5 shrink-0" />
                                <div>
                                    <span className="font-bold text-stone-900">Evidence-First Prompting</span>
                                    <p className="text-xs text-stone-500 mt-0.5">The orchestration layer is instructed to use *only* the provided evidence nodes from the graph.</p>
                                </div>
                            </li>
                            <li className="flex gap-3">
                                <div className="w-1.5 h-1.5 rounded-full bg-fodda-accent mt-1.5 shrink-0" />
                                <div>
                                    <span className="font-bold text-stone-900">Source Attribution</span>
                                    <p className="text-xs text-stone-500 mt-0.5">Every fact in a deterministic response is linked to a permanent <code className="bg-stone-100 px-1 py-0.5 rounded text-stone-800">ArticleID</code> or <code className="bg-stone-100 px-1 py-0.5 rounded text-stone-800">TrendID</code>.</p>
                                </div>
                            </li>
                        </ul>
                    </section>

                    <section className="pt-6 border-t border-stone-100">
                        <h4 className="text-[10px] font-bold text-stone-400 uppercase tracking-[0.2em] mb-4">How it Works</h4>
                        <div className="space-y-3">
                            <div className="flex items-center gap-3 bg-stone-50 p-3 rounded-lg border border-stone-100">
                                <span className="w-5 h-5 flex items-center justify-center bg-stone-200 rounded text-[10px] font-bold">1</span>
                                <span className="text-xs font-medium">Query Parsing & Vertical Identification</span>
                            </div>
                            <div className="flex items-center gap-3 bg-stone-50 p-3 rounded-lg border border-stone-100">
                                <span className="w-5 h-5 flex items-center justify-center bg-stone-200 rounded text-[10px] font-bold">2</span>
                                <span className="text-xs font-medium">Directed Graph Traversal in Neo4j</span>
                            </div>
                            <div className="flex items-center gap-3 bg-stone-50 p-3 rounded-lg border border-stone-100">
                                <span className="w-5 h-5 flex items-center justify-center bg-stone-200 rounded text-[10px] font-bold">3</span>
                                <span className="text-xs font-medium">Strict Synthesis using Filtered Evidence Nodes</span>
                            </div>
                        </div>
                    </section>
                </div>

                <div className="p-4 bg-stone-900 flex justify-between items-center shrink-0">
                    <p className="text-[10px] text-stone-500 font-bold uppercase tracking-widest px-4">Integrity Engine v1.5.1</p>
                    <button onClick={onClose} className="px-6 py-2 bg-stone-800 text-stone-100 rounded-lg text-xs font-bold uppercase tracking-widest hover:bg-fodda-accent transition-colors">Close</button>
                </div>
            </div>
        </div>
    );
};
