
import React from 'react';

interface DeterministicModalProps {
    isOpen: boolean;
    onClose: () => void;
}

export const DeterministicModal: React.FC<DeterministicModalProps> = ({ isOpen, onClose }) => {
    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-[250] flex items-center justify-center p-4">
            <div className="absolute inset-0 bg-ink/40 backdrop-blur-md" onClick={onClose} />
            <div className="relative w-full max-w-2xl bg-white rounded-3xl shadow-2xl overflow-hidden animate-fade-in-up border border-line flex flex-col max-h-[90vh]">
                <div className="p-6 border-b border-line flex justify-between items-center bg-cream shrink-0">
                    <div className="flex items-center space-x-3">
                        <div className="bg-brand-soft p-2 rounded-lg border border-brand/10">
                            <svg className="w-5 h-5 text-brand" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" /></svg>
                        </div>
                        <h3 className="font-serif italic text-xl text-ink">Deterministic Mode</h3>
                    </div>
                    <button onClick={onClose} className="p-2 text-ink-4 hover:text-ink transition-colors">
                        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>
                    </button>
                </div>

                <div className="p-8 space-y-8 overflow-y-auto text-ink-2 leading-relaxed text-sm scrollbar-hide bg-white">
                    <section>
                        <h4 className="eyebrow mb-4">Grounded Retrieval</h4>
                        <p className="text-ink-2">
                            Deterministic Mode ensures that every response generated by the AI is strictly grounded in the knowledge graph. If the required information is not present in the graph, the system will not "hallucinate" or generate synthetic facts.
                        </p>
                    </section>

                    <section className="pt-6 border-t border-line">
                        <h4 className="eyebrow mb-4">Technical Safeguards</h4>
                        <ul className="space-y-6">
                            <li className="flex gap-4">
                                <div className="w-1.5 h-1.5 rounded-full bg-brand mt-1.5 shrink-0" />
                                <div>
                                    <span className="font-bold text-ink">NO_MATCH Fallback</span>
                                    <p className="text-xs text-ink-3 mt-1 leading-relaxed">When graph retrieval returns zero-confidence matches, the API returns a structured <code className="bg-cream px-1.5 py-0.5 rounded text-ink-2 font-mono border border-line">NO_MATCH</code> status code instead of a synthetic guess.</p>
                                </div>
                            </li>
                            <li className="flex gap-4">
                                <div className="w-1.5 h-1.5 rounded-full bg-brand mt-1.5 shrink-0" />
                                <div>
                                    <span className="font-bold text-ink">Evidence-Locked Prompting</span>
                                    <p className="text-xs text-ink-3 mt-1 leading-relaxed">The orchestration layer is strictly instructed to use *only* the provided evidence nodes from the graph. External knowledge injection is suppressed.</p>
                                </div>
                            </li>
                            <li className="flex gap-4">
                                <div className="w-1.5 h-1.5 rounded-full bg-brand mt-1.5 shrink-0" />
                                <div>
                                    <span className="font-bold text-ink">Source Attribution</span>
                                    <p className="text-xs text-ink-3 mt-1 leading-relaxed">Every fact in a deterministic response is linked to a permanent <code className="bg-cream px-1.5 py-0.5 rounded text-ink-2 font-mono border border-line">ArticleID</code> or <code className="bg-cream px-1.5 py-0.5 rounded text-ink-2 font-mono border border-line">TrendID</code> for auditability.</p>
                                </div>
                            </li>
                        </ul>
                    </section>

                    <section className="pt-6 border-t border-line">
                        <h4 className="eyebrow mb-4">How it Works</h4>
                        <div className="space-y-3">
                            <div className="flex items-center gap-4 bg-paper p-4 rounded-xl border border-line">
                                <span className="w-6 h-6 flex items-center justify-center bg-cream border border-line rounded text-[11px] font-bold text-ink">1</span>
                                <span className="text-xs font-bold text-ink-2">Query Parsing & Vertical Identification</span>
                            </div>
                            <div className="flex items-center gap-4 bg-paper p-4 rounded-xl border border-line">
                                <span className="w-6 h-6 flex items-center justify-center bg-cream border border-line rounded text-[11px] font-bold text-ink">2</span>
                                <span className="text-xs font-bold text-ink-2">Directed Graph Traversal in Neo4j</span>
                            </div>
                            <div className="flex items-center gap-4 bg-paper p-4 rounded-xl border border-line">
                                <span className="w-6 h-6 flex items-center justify-center bg-cream border border-line rounded text-[11px] font-bold text-ink">3</span>
                                <span className="text-xs font-bold text-ink-2">Strict Synthesis using Filtered Evidence Nodes</span>
                            </div>
                        </div>
                    </section>
                </div>

                <div className="p-5 bg-ink flex justify-between items-center shrink-0">
                    <p className="text-[10px] text-cream/40 font-bold uppercase tracking-widest px-4">Integrity Engine v1.5.1</p>
                    <button onClick={onClose} className="px-8 py-2.5 bg-brand text-white rounded-lg text-xs font-bold uppercase tracking-widest hover:bg-brand-dark transition-all shadow-lg shadow-brand/20">Close</button>
                </div>
            </div>
        </div>
    );
};
