import React, { useState, useRef, useEffect, useMemo } from 'react';
import ReactMarkdown from 'react-markdown';
import { Message, Vertical } from '../types';

interface ChatInterfaceProps {
  messages: Message[];
  isProcessing: boolean;
  vertical: Vertical;
  onSendMessage: (msg: string) => void;
  onAnchorClick?: (type: 'trend' | 'article', id: string) => void;
  onToggleSidebar: () => void;
  onToggleEvidence: () => void;
}

// Internal component to handle the staggered reveal of the message
const StaggeredMessageContent: React.FC<{ content: string; isNew: boolean; onAnchorClick?: (type: 'trend' | 'article', id: string) => void }> = ({ content, isNew, onAnchorClick }) => {
  const sections = useMemo(() => {
    if (!content) return [];
    // Split on newline followed by #, or start of string followed by #.
    return content.split(/(?=\n#|(?<=^)#)/g);
  }, [content]);

  // Shared markdown components configuration
  const markdownComponents = {
    // H1 and H2 remain Serif for Editorial/Summary feel
    h1: ({node, ...props}: any) => <h1 className="font-serif text-sm font-bold text-stone-900 uppercase tracking-widest mt-4 mb-3 border-b border-stone-100 pb-1" {...props} />,
    h2: ({node, ...props}: any) => <h2 className="font-serif text-xs font-bold text-stone-900 uppercase tracking-widest mt-6 mb-2" {...props} />,
    
    // H3 changed to Sans-Serif to match Evidence Cards style
    h3: ({node, ...props}: any) => <h3 className="font-sans text-xs font-bold text-stone-800 uppercase tracking-wide mt-4 mb-2" {...props} />,
    
    a: ({node, href, children, ...props}: any) => {
      // Check for internal hash anchors generated by the LLM (e.g. #trend-1234)
      if (href?.startsWith('#trend-') || href?.startsWith('#article-')) {
        return (
          <a 
            href={href} 
            onClick={(e) => {
              e.preventDefault();
              if (onAnchorClick && href) {
                // remove the # prefix before parsing
                const cleanRef = href.substring(1); 
                const [type, id] = cleanRef.split('-');
                if ((type === 'trend' || type === 'article') && id) {
                  onAnchorClick(type, id);
                }
              }
            }}
            className="text-stone-900 font-bold hover:text-fodda-accent cursor-pointer transition-colors decoration-dotted underline hover:decoration-solid underline-offset-2"
            title="Click to locate in Evidence Drawer"
            {...props}
          >
            {children}
          </a>
        )
      }
      return <a href={href} className="text-fodda-accent underline" target="_blank" rel="noopener noreferrer" {...props}>{children}</a>
    }
  };

  if (!isNew) {
    return (
       <ReactMarkdown 
        className="prose prose-sm max-w-none 
          prose-p:text-stone-600 prose-p:leading-relaxed
          prose-li:text-stone-600 prose-ul:pl-4 prose-ol:pl-4
          prose-strong:text-stone-900 prose-strong:font-semibold
          prose-blockquote:border-l-2 prose-blockquote:border-fodda-accent prose-blockquote:bg-stone-50 prose-blockquote:py-1 prose-blockquote:px-4 prose-blockquote:not-italic prose-blockquote:text-stone-500"
        components={markdownComponents}
      >
        {content}
      </ReactMarkdown>
    );
  }

  return (
    <div className="space-y-1">
      {sections.map((section, index) => (
        <div 
          key={index} 
          className="opacity-0 animate-fade-in-up"
          style={{ animationDelay: `${index * 400}ms`, animationFillMode: 'forwards' }}
        >
          <ReactMarkdown 
            className="prose prose-sm max-w-none 
              prose-p:text-stone-600 prose-p:leading-relaxed
              prose-li:text-stone-600 prose-ul:pl-4 prose-ol:pl-4
              prose-strong:text-stone-900 prose-strong:font-semibold
              prose-blockquote:border-l-2 prose-blockquote:border-fodda-accent prose-blockquote:bg-stone-50 prose-blockquote:py-1 prose-blockquote:px-4 prose-blockquote:not-italic prose-blockquote:text-stone-500"
            components={markdownComponents}
          >
            {section}
          </ReactMarkdown>
        </div>
      ))}
    </div>
  );
};


export const ChatInterface: React.FC<ChatInterfaceProps> = ({ messages, isProcessing, vertical, onSendMessage, onAnchorClick, onToggleSidebar, onToggleEvidence }) => {
  const [input, setInput] = useState('');
  const [isUserMenuOpen, setIsUserMenuOpen] = useState(false);
  const endOfMessagesRef = useRef<HTMLDivElement>(null);
  const lastMessageIdRef = useRef<string | null>(null);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() || isProcessing) return;
    onSendMessage(input);
    setInput('');
  };

  useEffect(() => {
    const lastMsg = messages[messages.length - 1];
    const isUser = lastMsg?.role === 'user';
    
    // Only scroll to bottom if it's a user message or we are processing (loading state)
    // If it's an assistant message, we leave the scroll where it is (likely at the top of the new message)
    if (isProcessing || isUser) {
      endOfMessagesRef.current?.scrollIntoView({ behavior: 'smooth' });
    }

    if (messages.length > 0) {
      lastMessageIdRef.current = messages[messages.length - 1].id;
    }
  }, [messages, isProcessing]);

  const downloadText = (text: string, filename: string) => {
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex-1 flex flex-col h-full bg-stone-50/30 relative">
      {/* Header */}
      <div className="h-16 border-b border-stone-200 flex items-center justify-between px-4 md:px-6 bg-white/90 backdrop-blur-md sticky top-0 z-30 shadow-sm">
        
        <div className="flex items-center">
          {/* Hamburger Menu (Mobile) */}
          <button 
            onClick={onToggleSidebar}
            className="md:hidden p-2 -ml-2 mr-2 text-stone-500 hover:text-stone-700 hover:bg-stone-100 rounded-md transition-colors"
          >
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" /></svg>
          </button>
          
          {/* Mobile Fodda Logo */}
          <span className="font-serif font-bold text-lg text-stone-900 mr-3 md:hidden tracking-tight">Fodda</span>

          {/* Vertical Badge - Full text always */}
          <span className="text-xs font-bold bg-stone-900 text-white px-2 py-0.5 rounded mr-3 uppercase tracking-wider inline-block">
            {vertical}
          </span>
          
          {/* Research Assistant - Always visible */}
          <span className="text-sm text-stone-600 font-medium inline-block whitespace-nowrap">Research Assistant</span>
        </div>

        {/* Right Side Actions */}
        <div className="flex items-center space-x-2 md:space-x-4">
          
          {/* Mobile Evidence Toggle */}
          <button 
            onClick={onToggleEvidence}
            className="md:hidden flex items-center space-x-1 p-2 text-fodda-accent hover:bg-purple-50 rounded-md transition-colors"
          >
            <span className="text-xs font-bold uppercase hidden sm:inline">Evidence</span>
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01" /></svg>
          </button>

          {/* User Menu */}
          <div className="relative">
            <button 
              onClick={() => setIsUserMenuOpen(!isUserMenuOpen)}
              className="flex items-center space-x-2 focus:outline-none group"
            >
              <div className="w-8 h-8 rounded-full bg-stone-200 border border-stone-300 flex items-center justify-center text-xs font-bold text-stone-600 group-hover:bg-fodda-accent group-hover:text-white group-hover:border-fodda-accent transition-all">
                JD
              </div>
            </button>

            {/* Dropdown */}
            {isUserMenuOpen && (
              <>
                <div className="fixed inset-0 z-40" onClick={() => setIsUserMenuOpen(false)}></div>
                <div className="absolute right-0 top-full mt-2 w-48 bg-white rounded-lg shadow-xl border border-stone-200 z-50 overflow-hidden animate-fade-in-up origin-top-right">
                  <div className="px-4 py-3 border-b border-stone-100 bg-stone-50">
                    <p className="text-sm font-semibold text-stone-900">John Doe</p>
                    <p className="text-xs text-stone-500 truncate">demo@fodda.ai</p>
                  </div>
                  <div className="py-1">
                    <button onClick={() => setIsUserMenuOpen(false)} className="w-full text-left px-4 py-2 text-sm text-stone-700 hover:bg-stone-50 flex items-center">
                      <svg className="w-4 h-4 mr-2 text-stone-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" /></svg>
                      Account
                    </button>
                    <button onClick={() => setIsUserMenuOpen(false)} className="w-full text-left px-4 py-2 text-sm text-stone-700 hover:bg-stone-50 flex items-center">
                      <svg className="w-4 h-4 mr-2 text-stone-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>
                      Token Use
                    </button>
                    <button onClick={() => setIsUserMenuOpen(false)} className="w-full text-left px-4 py-2 text-sm text-stone-700 hover:bg-stone-50 flex items-center">
                      <svg className="w-4 h-4 mr-2 text-stone-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z" /></svg>
                      Billing
                    </button>
                  </div>
                  <div className="border-t border-stone-100 py-1">
                    <button onClick={() => setIsUserMenuOpen(false)} className="w-full text-left px-4 py-2 text-sm text-red-600 hover:bg-red-50 flex items-center">
                      <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" /></svg>
                      Log Out
                    </button>
                  </div>
                </div>
              </>
            )}
          </div>
        </div>

      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto px-4 md:px-6 py-6 space-y-8 scroll-smooth">
        {messages.length === 0 && (
          <div className="h-full flex flex-col items-center justify-center text-stone-400 pb-20 opacity-60">
             <svg className="w-16 h-16 mb-4 text-stone-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1} d="M19.428 15.428a2 2 0 00-1.022-.547l-2.384-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" />
             </svg>
             <p className="text-sm font-medium tracking-wide">Query this Fodda Graph</p>
          </div>
        )}
        
        {messages.map((msg, index) => {
          const isLatest = index === messages.length - 1;
          const shouldAnimate = isLatest && msg.role === 'assistant';

          return (
            <div key={msg.id} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
              {msg.role === 'user' ? (
                <div className="max-w-[85%] md:max-w-2xl bg-stone-900 text-white rounded-2xl rounded-tr-none px-5 py-3 shadow-lg">
                  <p className="text-sm leading-relaxed whitespace-pre-wrap">{msg.content}</p>
                </div>
              ) : (
                <div className="max-w-full md:max-w-3xl w-full bg-white rounded-xl shadow-sm border border-stone-200 overflow-hidden">
                   <div className="h-1 bg-fodda-accent w-full"></div>
                   <div className="p-4 md:p-5">
                      <StaggeredMessageContent 
                        content={msg.content} 
                        isNew={shouldAnimate} 
                        onAnchorClick={onAnchorClick}
                      />
                   </div>
                   <div className="bg-stone-50 px-4 md:px-5 py-3 border-t border-stone-100 flex flex-wrap gap-y-2 justify-between items-center">
                      <div className="flex items-center space-x-2">
                          <span className="text-[10px] uppercase tracking-wider text-stone-400 font-semibold">Fodda Intelligence</span>
                      </div>
                      
                      {/* Clustered Buttons with visual separation */}
                      <div className="flex items-center">
                        <div className="h-4 w-px bg-stone-200 mx-3 hidden xs:block"></div> {/* Divider */}
                        <div className="flex items-center -space-x-px">
                          <button 
                            onClick={() => downloadText(msg.content, `fodda-export-${msg.id}.txt`)}
                            className="group flex items-center justify-center px-2 py-1 bg-white border border-stone-200 hover:bg-stone-50 hover:border-stone-300 hover:z-10 rounded-l transition-all"
                            title="Download as TXT"
                          >
                            <span className="text-[9px] font-bold text-stone-500 group-hover:text-stone-800">TXT</span>
                          </button>
                          <button className="group flex items-center justify-center px-2 py-1 bg-stone-50 border border-stone-200 cursor-not-allowed opacity-60" title="PDF Export">
                            <span className="text-[9px] font-bold text-stone-400">PDF</span>
                          </button>
                          <button className="group flex items-center justify-center px-2 py-1 bg-stone-50 border border-stone-200 cursor-not-allowed opacity-60" title="DOC Export">
                            <span className="text-[9px] font-bold text-stone-400">DOC</span>
                          </button>
                           <button className="group flex items-center justify-center px-2 py-1 bg-stone-50 border border-stone-200 rounded-r cursor-not-allowed opacity-60" title="PPT Export">
                            <span className="text-[9px] font-bold text-stone-400">PPT</span>
                          </button>
                        </div>
                      </div>
                   </div>
                </div>
              )}
            </div>
          );
        })}
        
        {isProcessing && (
          <div className="flex justify-start w-full max-w-3xl">
            <div className="bg-white px-6 py-4 rounded-xl border border-stone-200 shadow-sm flex items-center space-x-3 w-full">
              <div className="flex space-x-1">
                <div className="w-1.5 h-1.5 bg-fodda-accent rounded-full animate-bounce" style={{ animationDelay: '0ms' }}></div>
                <div className="w-1.5 h-1.5 bg-fodda-accent rounded-full animate-bounce" style={{ animationDelay: '150ms' }}></div>
                <div className="w-1.5 h-1.5 bg-fodda-accent rounded-full animate-bounce" style={{ animationDelay: '300ms' }}></div>
              </div>
              <span className="text-xs text-stone-400 font-medium uppercase tracking-wide">Synthesizing {vertical} Data...</span>
            </div>
          </div>
        )}
        <div ref={endOfMessagesRef} />
      </div>

      {/* Input Area */}
      <div className="p-4 md:p-6 bg-white/80 backdrop-blur border-t border-stone-200 z-20">
        <form onSubmit={handleSubmit} className="relative max-w-3xl mx-auto">
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder={`Ask about ${vertical.toLowerCase()}...`}
            className="w-full bg-stone-50 border border-stone-200 text-stone-900 text-[16px] md:text-sm rounded-lg pl-5 pr-12 py-4 focus:outline-none focus:ring-1 focus:ring-stone-300 focus:border-stone-400 transition-all shadow-sm placeholder:text-stone-400"
            disabled={isProcessing}
          />
          <button
            type="submit"
            disabled={!input.trim() || isProcessing}
            className="absolute right-3 top-1/2 -translate-y-1/2 p-2 bg-white text-stone-400 hover:text-fodda-accent disabled:opacity-30 rounded-md transition-colors border border-stone-100 shadow-sm"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14 5l7 7m0 0l-7 7m7-7H3" />
            </svg>
          </button>
        </form>
      </div>
    </div>
  );
};