
import { Vertical, Trend, Article } from './types';

export const SUGGESTED_QUESTIONS: Record<Vertical, string[]> = {
  [Vertical.Retail]: [
    "What retail trends are shaping how brands use physical stores today?",
    "What’s changing in how retailers use technology to engage customers in-store?",
    "What trends are influencing how retailers think about convenience and speed?",
    "What are retailers experimenting with to create more differentiated shopping experiences?"
  ],
  [Vertical.Sports]: [
    "What’s changing in how fans engage with sports outside of live games?",
    "How is technology reshaping athlete training and performance?",
    "What’s driving growth in women’s sports right now?",
    "How are leagues or teams experimenting with new revenue streams?"
  ],
  [Vertical.Beauty]: [
    "What’s changing in beauty around personalization and diagnostics?",
    "How are beauty brands using biotech or new ingredients?",
    "What’s driving the overlap between beauty and wellness?",
    "How are beauty brands responding to sustainability expectations?"
  ]
};

export const MOCK_TRENDS: Trend[] = [
  // --- RETAIL ---
  { trendId: "5367", vertical: Vertical.Retail, trendName: "Short-Run Co-Branded Pop-Up Retail Installations", trendDescription: "Brands and retail partners open temporary, co-branded pop-up locations to launch limited product drops and curated experiences aimed at driving immediate foot traffic, email/social captures and PR." },
  { trendId: "5368", vertical: Vertical.Retail, trendName: "Computer Vision and AI Agent-Assisted In-Store Shopping", trendDescription: "Stores deploy computer vision, virtual try-on tech, conversational AI agents and robotics to guide product selection and fitting, while cashierless or automated checkout systems speed transactions." },
  { trendId: "5369", vertical: Vertical.Retail, trendName: "Premium Prepared-Food Programs", trendDescription: "Grocers, convenience chains and quick-service operators expand chef partnerships, higher-quality ready-to-eat meals and premium private-label items to capture additional dayparts." },
  { trendId: "5370", vertical: Vertical.Retail, trendName: "Targeted Store Expansion and Format Pilots", trendDescription: "Well-funded operators accelerate new store openings and pilot distinct formats—flagship locations, experience-focused stores and takeout-only footprints—to secure local catchment." },
  { trendId: "5372", vertical: Vertical.Retail, trendName: "Geo-Triggered Commerce Enabled by Marketplaces", trendDescription: "Marketplaces, real-time discovery tools and rapid last-mile logistics are integrated to trigger offers and fulfillment when consumers are nearby." },
  { trendId: "5373", vertical: Vertical.Retail, trendName: "Service-First Retail Stores", trendDescription: "Retailers prioritize in-store services—repairs, clinics, click-and-collect, specialist consultations—to mitigate margin pressure, drive habitual visits and increase customer lifetime value." },
  { trendId: "5374", vertical: Vertical.Retail, trendName: "Retail-Integrated Resale and Curated Pre-Owned Assortments", trendDescription: "Retailers adopt standardized refurbishment and resale programs to capture secondary market value, offering circular commerce options that respond to margin pressure and sustainability goals." },
  { trendId: "5422", vertical: Vertical.Retail, trendName: "Airport Retail & Passenger Experience Elevation", trendDescription: "Airports become experiential retail and service platforms (luxury flagships, meet & greet, autonomous delivery, immersive activations) to monetize dwell time." },
  { trendId: "5602", vertical: Vertical.Retail, trendName: "Background AI Agents for Revenue Ops", trendDescription: "Background AI agents for on-site revenue operations and storefront automation that recommend or execute pricing, transfers, and next-best-actions at SKU-level." },
  { trendId: "5603", vertical: Vertical.Retail, trendName: "Conversational & Visual AI Shopping Advisors", trendDescription: "Conversational and visual AI shopping advisors that close the loop from dialogue/vision to checkout across brand apps and platforms." },
  { trendId: "5604", vertical: Vertical.Retail, trendName: "Creator-Driven Resale, Drops & Circular Commerce", trendDescription: "Creator-driven resale, scheduled drops and circular commerce that monetize scarcity, authenticated secondary markets and sustainability-driven resale programs." },
  { trendId: "5605", vertical: Vertical.Retail, trendName: "Autonomous Pricing/Promo Agents", trendDescription: "Autonomous pricing/promo agents and AI‑native shopping channels collapse discovery and transaction into a single flow." },
  { trendId: "5609", vertical: Vertical.Retail, trendName: "Physical Retail Automation & Robotics", trendDescription: "Customer-facing retail automation and robotics pilots that reconfigure in-store labor and last-mile delivery economics through autonomous units and robotic stores." },
  { trendId: "5610", vertical: Vertical.Retail, trendName: "Gamified, Compact Formats", trendDescription: "Gamified compact formats use scarcity, randomness and collectible narratives (vending, blind‑boxes, drops) to drive frequent, low‑ticket purchases and social virality." },
  { trendId: "5611", vertical: Vertical.Retail, trendName: "Controlled Off‑Price & Brand‑Safe Secondary Channels", trendDescription: "Brands create controlled off‑price and brand‑safe secondary channels—buyback, refurb and members‑only sales—to recover inventory value while protecting primary pricing." },
  { trendId: "5613", vertical: Vertical.Retail, trendName: "Retail Operational AI & Infrastructure", trendDescription: "Retail operations are being rearchitected with AI, geospatial decisioning and modular services to cut cost‑to‑serve and enable omnichannel promises." },
  { trendId: "5614", vertical: Vertical.Retail, trendName: "Seamless Resale & Buyback Services", trendDescription: "Seamless resale and buyback services normalize circular commerce by embedding trade‑ins, authenticated refurb and creator consignment into retail flows." },

  // --- SPORTS ---
  { trendId: "5441", vertical: Vertical.Sports, trendName: "Team Kits as Culture, Music & Lifestyle Activation Vehicles", trendDescription: "Clubs and rights-holders are converting kits into episodic, culturally framed lifestyle products that carry narrative, music and purpose beyond team identity." },
  { trendId: "5442", vertical: Vertical.Sports, trendName: "Rights-Led Sports Media Convergence", trendDescription: "Rights holders convert single-asset deals into ongoing media stacks—venue IP, owned channels, and identity products—to create recurring fan commerce and first-party data." },
  { trendId: "5444", vertical: Vertical.Sports, trendName: "Boutique Fitness Formats Scaling via Franchising", trendDescription: "Specialty training formats are being productized into franchisable studios, club integrations and eventized competitions to drive retention and unit economics." },
  { trendId: "5447", vertical: Vertical.Sports, trendName: "Athlete‑Driven Consumer Product Lines", trendDescription: "Athletes’ equity is being translated into adjacent consumer categories and structured licensing to monetize fan trust across regions and categories." },
  { trendId: "5450", vertical: Vertical.Sports, trendName: "Sensor‑Verified Personalization", trendDescription: "Sensor‑verified personalization and injury‑load management convert continuous sensor data into prescriptive coaching and injury‑risk alerts for athletes at all levels." },
  { trendId: "5454", vertical: Vertical.Sports, trendName: "AI‑Guided Home Strength Systems", trendDescription: "AI‑guided home strength systems combine sensing, computer vision and adaptive resistance to deliver studio‑grade guidance and measurable progress at home." },
  { trendId: "5456", vertical: Vertical.Sports, trendName: "Fan Data, Personalization & Sponsorship Measurement", trendDescription: "Rights holders and vendors investing in AI, personalization and measurement tools to personalize fan experiences and quantify sponsor ROI." },
  { trendId: "5458", vertical: Vertical.Sports, trendName: "Sensor + Recovery Convergence", trendDescription: "Clubs integrate recovery and wellness modalities (cold plunges, red light, nervous‑system tech) as core offerings paired with apps to boost retention and ancillary revenue." },
  { trendId: "5459", vertical: Vertical.Sports, trendName: "Women’s Sport Participation & Player‑First Commercialization", trendDescription: "Design, programming and commercial models are aligning to remove participation barriers in women’s sport and redirect economic value to players and communities." },
  { trendId: "5462", vertical: Vertical.Sports, trendName: "Standardized Franchise & Multi‑Brand Scaling", trendDescription: "Standardized franchise and multi‑brand scaling leverages modular studio formats, franchisor tooling and proven unit economics to roll out rapidly and capital‑efficiently." },
  { trendId: "5556", vertical: Vertical.Sports, trendName: "Tech Partnerships Upgrading Live Sports Operations", trendDescription: "Venue and rights-holder tech partnerships integrate payments, mobility, remote production and analytics to reduce costs, create sponsorable inventory, and improve fan experience." },
  { trendId: "5560", vertical: Vertical.Sports, trendName: "Eventized Fitness", trendDescription: "Fitness packaged as ticketed, social entertainment—touring competitions, social sports venues and fitness cruises—monetized via sponsorships, F&B and ticketing." },
  { trendId: "5564", vertical: Vertical.Sports, trendName: "Human-Led, Tech-Enabled Coaching", trendDescription: "Human coaching scaled with AI, sensors and AR to deliver measurable, cross-channel training while preserving human relationships." },
  { trendId: "5573", vertical: Vertical.Sports, trendName: "Modular & Multifunctional Sports Infrastructure", trendDescription: "Flexible venue and equipment systems enable rapid reconfiguration, mixed-use programming and integrated data capture for year-round monetization." },
  { trendId: "5575", vertical: Vertical.Sports, trendName: "Adaptive & Inclusive Fitness Equipment", trendDescription: "Adaptive and inclusive equipment/apparel designs broaden accessibility across institutions and everyday users." },

  // --- BEAUTY ---
  { trendId: "5389", vertical: Vertical.Beauty, trendName: "Scented Experiences & Fragrance Extensions", trendDescription: "Fragrance and scent experiences expand beyond bottles into wearables, accessories, spirits and place-based narratives to create multisensory brand touchpoints and repeatable rituals." },
  { trendId: "5391", vertical: Vertical.Beauty, trendName: "Immersive & Experiential Fragrance Retail", trendDescription: "Theatrical IRL moments (pop-ups, destination stores, late-night drops) used as discovery funnels." },
  { trendId: "5392", vertical: Vertical.Beauty, trendName: "Tech & Science-Led Fragrance", trendDescription: "Neuroscience, transparency and customization are reframing perfumery as measurable sensory science." },
  { trendId: "5393", vertical: Vertical.Beauty, trendName: "Discovery, Refill & Pre-Order Convenience", trendDescription: "Sampler systems, refill fountains and pre-order pickup reduce friction and boost repurchase in fragrance retail." },
  { trendId: "5395", vertical: Vertical.Beauty, trendName: "Pleasure & Sexual Wellness in Personal Care", trendDescription: "Products explicitly designed and marketed around sensual pleasure, texture and intimacy." },
  { trendId: "5396", vertical: Vertical.Beauty, trendName: "Provenance & Botanical Storytelling", trendDescription: "Terroir-led narratives and traceable sourcing premiumize niche fragrances with authentic origin stories." },
  { trendId: "5397", vertical: Vertical.Beauty, trendName: "Fragrance IP & Collaboration Extensions", trendDescription: "Fragrance becomes a storytelling platform—expanding through entertainment, character IP, and cultural collaborations." },
  { trendId: "5545", vertical: Vertical.Beauty, trendName: "Celebrity & Influencer-Led Fragrance Entrepreneurship", trendDescription: "Creators and athletes leverage audience equity to launch scalable fragrance IP via DTC, licensing and retail exclusives." },
  { trendId: "5547", vertical: Vertical.Beauty, trendName: "Neuroscience & Data-Driven Fragrance", trendDescription: "Suppliers and brands use neuroscience, large datasets and AI to design scents targeting emotional outcomes." },
  { trendId: "5551", vertical: Vertical.Beauty, trendName: "Novel Scent Formats & Delivery Mechanisms", trendDescription: "Fragrance is expanding beyond bottles into edible, wearable, embedded and tech-integrated formats." },
  { trendId: "5552", vertical: Vertical.Beauty, trendName: "Conversion‑Linked Discovery Engines", trendDescription: "Discovery engineered to directly drive attributable sales through sampling linked to redemption, AR try‑ons and AI matching." },
  { trendId: "5558", vertical: Vertical.Beauty, trendName: "One‑Step Performance", trendDescription: "Multi‑function formulations that combine credible actives into one‑step hero SKUs, simplifying routines while delivering clinical outcomes." },
  { trendId: "5563", vertical: Vertical.Beauty, trendName: "Design‑Led Luxury & Experiential Objects", trendDescription: "Transforming products and pop‑ups into collectible ritual objects and cultural moments to justify premium pricing." },
  { trendId: "5579", vertical: Vertical.Beauty, trendName: "Beauty Devices & Spa Automation", trendDescription: "Clinic‑grade energy and delivery platforms miniaturized for at-home use or integrated into retail clinics." },
  { trendId: "5581", vertical: Vertical.Beauty, trendName: "China’s Regional Beauty Acceleration", trendDescription: "Policy, targeted finance and expos operate as a coordinated commercialization engine shortening time‑to‑market." },
  { trendId: "5583", vertical: Vertical.Beauty, trendName: "Salon & Spa Tech Professionalization", trendDescription: "Adoption of enterprise tech, AI tools and credentialing to professionalize services and increase throughput." },
  { trendId: "5593", vertical: Vertical.Beauty, trendName: "K‑Beauty Globalization", trendDescription: "K‑beauty R&D and manufacturing expertise exported via co‑development and localized formulation to enable region‑specific rollouts." },
  { trendId: "5594", vertical: Vertical.Beauty, trendName: "Beauty Devices & Clinic→Home Tech", trendDescription: "Miniaturized energy tech, clearer regulatory pathways and consumer demand for clinic‑level results at home reduce adoption friction." },
  { trendId: "5595", vertical: Vertical.Beauty, trendName: "Hybrid Makeup‑Skincare / Skip‑Care Bases", trendDescription: "Makeup bases that consolidate skincare actives and coverage into single clinically positioned SKUs." },
];

export const MOCK_ARTICLES: Article[] = [
  // --- RETAIL ---
  { articleId: "7885", vertical: Vertical.Retail, trendIds: ["5367"], title: "Marc Jacobs and Nordstrom NYC: Fashion Meets Art", sourceUrl: "https://www.shopdropdaily.com/post/marc-jacobs-joy-pop-up-at-the-corner-nordstrom-nyc", snippet: "Marc Jacobs and Nordstrom have launched a pop-up called 'Marc Jacobs at The Corner', integrating fashion, art, and community engagement." },
  { articleId: "8052", vertical: Vertical.Retail, trendIds: ["5367"], title: "Carnaby Street Transformed: Barbour x FARM Rio", sourceUrl: "https://www.shopdropdaily.com/post/barbour-farm-rio-collection-takeover-carnaby-st-london", snippet: "Barbour collaborated with FARM Rio to transform its Carnaby Street store into a vibrant tropical escape with bold prints and lush foliage." },
  { articleId: "7185", vertical: Vertical.Retail, trendIds: ["5368"], title: "Grupo Boticário's AI Assistant Elevates Sales", sourceUrl: "https://abramark.com.br/destaques/grupo-boticario-revoluciona-e-commerce-com-ia-inspirada-em-uma-consultora-de-beleza-que-cria-rotinas-recomendacoes-personalizadas-e-ainda-ajuda-a-escolher-presentes/", snippet: "Grupo Boticário introduced an AI virtual assistant for their e-commerce app, offering personalized recommendations and support, boosting sales conversion by 46%." },
  { articleId: "5937", vertical: Vertical.Retail, trendIds: ["5368"], title: "Ralph Lauren Launches AI Styling Bot", sourceUrl: "https://www.businessoffashion.com/articles/technology/ralph-lauren-launches-ai-styling-bot-ask-ralph/", snippet: "Ralph Lauren introduced 'Ask Ralph,' an AI styling bot in their US app, offering real-time product recommendations and outfit guidance." },
  { articleId: "5875", vertical: Vertical.Retail, trendIds: ["5369"], title: "7-Eleven's Limit Over Series Surpasses 1 Million Sales", sourceUrl: "https://www.ddaily.co.kr/page/view/2025090913381178268", snippet: "7-Eleven introduced the 'Limit Over Series' of larger ready meals, exceeding 1 million sales with the launch of the 'Barbecue Beef Bento.'" },
  { articleId: "7582", vertical: Vertical.Retail, trendIds: ["5370"], title: "Aldi UK’s £1.6 Billion Expansion", sourceUrl: "https://www.esmmagazine.com/retail/aldi-uk-commits-1-6-billion-to-ramp-up-store-expansion-296165", snippet: "Aldi UK is investing £1.6 billion to open 80 new stores to address grocery margin pressure and expand reach." },
  { articleId: "7240", vertical: Vertical.Retail, trendIds: ["5370"], title: "Casey’s Announces 500 New Stores", sourceUrl: "https://news.google.com/rss/articles/CBMi0AFBVV95cUxPQ2NiOF9mbGpZNzduWlkybTVBQlJZWl9QTEZBMVdMVWtrbzY1dUs3d29QMFE3Vlh4bnlyNi1JMzhXdnN5ZlctMXY2bWpRZmtyR00waElTLXRFeVNvZGpQX1lXVXN4bkxJRmFnVHBTSVMwVzVHVVJTZTQwMGk1b3dyQ0JjVTRVNHdVemd0QTJYODFVdjNnSnBzNkZMam9HdXhPand1UjI2U2lUa3ljVS0zOWppY0FWZW0tMkN5ZHc1TlZzRUlqeDhiQVFiZnRLY0xC", snippet: "Casey's plans to open 500 new stores by September 2025 to boost scale and protect profitability against rising costs." },
  { articleId: "3424", vertical: Vertical.Retail, trendIds: ["5372"], title: "Fast Fashion Delivery: Flair's Lisbon Launch", sourceUrl: "https://www.nit.pt/compras/lojas-e-marcas/flair-nova-plataform-nacional-junta-varias-marcas-de-moda-e-tem-entregas-em-2-horas", snippet: "Flair introduced a platform in Lisbon for fast, two-hour delivery of fashion items from ten partner brands." },
  { articleId: "6412", vertical: Vertical.Retail, trendIds: ["5374"], title: "Amazon Renewed: Trustworthy Refurbished Options", sourceUrl: "https://www.amazon.com/renewed", snippet: "Amazon Renewed offers certified refurbished products to help retailers recover margin on returned items while offering value to shoppers." },
  { articleId: "9126", vertical: Vertical.Retail, trendIds: ["5422"], title: "Transforming Changi Airport: Jewel Changi", sourceUrl: "https://www.changiairport.com/en/jewel.html", snippet: "Jewel Changi enhances Singapore Changi Airport with retail, dining, and attractions like the Rain Vortex, turning passenger dwell time into revenue." },
  { articleId: "11755", vertical: Vertical.Retail, trendIds: ["5603", "5605"], title: "Dialog's AI Agent Boosts Conversion", sourceUrl: "https://www.eu-startups.com/2025/11/with-300k-add-to-cart-events-paris-based-dialog-secures-e3-7-million-round-to-scale-its-ai-shopping-agent/", snippet: "Dialog launched an AI agent for e-commerce that triples conversion rates by providing personalized customer interactions." },
  { articleId: "10423", vertical: Vertical.Retail, trendIds: ["5604", "5614"], title: "eBay and Emma Chamberlain's Charity Auction", sourceUrl: "https://www.tubefilter.com/2025/11/06/ebay-emma-chamberlain-charity-sale-luxury-fashion/", snippet: "eBay collaborated with Emma Chamberlain for creator-driven resale, highlighting circular commerce strategies to offset margin pressure." },
  { articleId: "10636", vertical: Vertical.Retail, trendIds: ["5610"], title: "Pop Mart's Times Square Flagship", sourceUrl: "https://retailboss.co/labubu-maker-pop-mart-launches-largest-u-s-flagship-times-square/", snippet: "Pop Mart signed a 10-year lease for a Times Square flagship, its largest U.S. retail move." },
  { articleId: "11464", vertical: Vertical.Retail, trendIds: ["5602", "5605"], title: "WOW AI - Sales Optimization", sourceUrl: "https://getwow.ai/en?utm_source=openai", snippet: "WOW AI uses real data to deliver accurate recommendations and smart strategies that boost conversions and increase sales." },
  { articleId: "5049", vertical: Vertical.Retail, trendIds: ["5609"], title: "Shenzhen's 6S Robot Store", sourceUrl: "https://news.google.com/rss/articles/CBMiVEFVX3lxTFAzUEY1X09SVmZsaVo5TE40SWk4SlhIUi11cDV1X1NQWXlPanFKbEVISVBMZ1NaTlFnSzRUMmgxZTExZF9HRUFCcW5YTjJfdlV5QkRGZg", snippet: "Shenzhen's Galaxy World CoCo Park launched the 'World's First 6S Robot Store,' featuring robots for snacks, coffee, and service to optimize labor costs." },
  { articleId: "11549", vertical: Vertical.Retail, trendIds: ["5611"], title: "Beko Expands Appliance Refurbishment", sourceUrl: "http://www.trendhunter.com/innovation/reduce-refurbish-recycle", snippet: "Beko is expanding its program to refurbish and resell used appliances, enhancing availability through outlet shops and partners." },
  { articleId: "8943", vertical: Vertical.Retail, trendIds: ["5613"], title: "Milkyway - Local Delivery App", sourceUrl: "https://www.milkywaydelivery.com", snippet: "A free Shopify app that unifies local delivery, doorstep returns, live tracking, and parcel protection for stores across the U.S." },

  // --- SPORTS ---
  { articleId: "7036", vertical: Vertical.Sports, trendIds: ["5441"], title: "Louis Vuitton Partners with Real Madrid Women’s Team", sourceUrl: "https://hypebae.com/2025/9/louis-vuitton-real-madrid-team-collaboration-formal-wear-release-date", snippet: "Louis Vuitton is collaborating with the Real Madrid women's football team to create exclusive Formal Wear." },
  { articleId: "3509", vertical: Vertical.Sports, trendIds: ["5441", "5459"], title: "Skims Expands in Sports: Partner of League One Volleyball", sourceUrl: "https://athletechnews.com/kim-kardashians-skims-teams-with-lovb-as-loungewear-partner/", snippet: "Skims partners with League One Volleyball to highlight female athletes and expand audience reach." },
  { articleId: "9375", vertical: Vertical.Sports, trendIds: ["5441", "5442"], title: "Spotify and FC Barcelona Extend Sponsorship", sourceUrl: "https://sportsmintmedia.com/fc-barcelona-and-spotify-strengthen-global-ties-with-extended-sponsorship-alliance/", snippet: "FC Barcelona and Spotify extended their sponsorship until 2030, creating new revenue through naming rights." },
  { articleId: "9439", vertical: Vertical.Sports, trendIds: ["5442"], title: "Whoopi Goldberg Launches Global Women's Sports Network", sourceUrl: "https://www.awsn.tv/about", snippet: "All Women’s Sports Network (AWSN) is a global 24/7 channel broadcasting women’s sports in 65 countries." },
  { articleId: "4906", vertical: Vertical.Sports, trendIds: ["5442", "5462"], title: "Pickleball's Evolution: Entertainment Hubs", sourceUrl: "https://athletechnews.com/pickleball-next-chapter-more-than-courts/", snippet: "Brands like The Pickle Pad combine social venues with dining and games to drive all-day dwell time." },
  { articleId: "1548", vertical: Vertical.Sports, trendIds: ["5462"], title: "PickleRage Aims for Nationwide Expansion", sourceUrl: "https://athletechnews.com/picklerage-inks-new-franchise-deals-across-us/", snippet: "PickleRage is expanding its indoor pickleball franchise with plans for over 500 locations." },
  { articleId: "5011", vertical: Vertical.Sports, trendIds: ["5447"], title: "Stanley 1913 Partners with Caitlin Clark", sourceUrl: "https://athletechnews.com/stanley-1913-partners-with-caitlin-clark-on-hydration-collection/", snippet: "Stanley 1913 is launching a signature hydration line with Caitlin Clark." },
  { articleId: "4917", vertical: Vertical.Sports, trendIds: ["5450"], title: "Virtuagym's Max AI Coach", sourceUrl: "https://athletechnews.com/virtuagym-launches-ai-fitness-coaching-tool-for-gyms-trainers/", snippet: "Virtuagym introduced Max AI Coach for creating quick, personalized workout plans." },
  { articleId: "1488", vertical: Vertical.Sports, trendIds: ["5454"], title: "AI-Powered Home Gym Revolutionizes Workouts", sourceUrl: "https://newatlas.com/fitness/aeke-k1-ai-coach-home-gym/", snippet: "The Aeke K1 home gym system offers an AI coach for personalized workouts." },
  { articleId: "1464", vertical: Vertical.Sports, trendIds: ["5458"], title: "Life Time Unveils Arden Hills Transformation", sourceUrl: "https://athletechnews.com/life-time-revives-former-arden-hills-club-with-eighth-california-location/", snippet: "Life Time has launched its eighth California location with upgraded fitness facilities." },
  { articleId: "4938", vertical: Vertical.Sports, trendIds: ["5459", "5575"], title: "ASICS Launches Inclusive PE Uniform", sourceUrl: "https://www.trendwatching.com/innovations/a-reimagived-pe-kit-by-asics-responds-to-girls-dropping-out-of-sports", snippet: "ASICS launched the Undropped Kit, a PE uniform designed to address discomfort." },
  { articleId: "11494", vertical: Vertical.Sports, trendIds: ["5556"], title: "CHEQ - in-venue mobile ordering", sourceUrl: "https://www.cheqplease.com/pepsi", snippet: "CHEQ technology powers friction-free purchases at stadiums to boost ancillary revenue." },
  { articleId: "12200", vertical: Vertical.Sports, trendIds: ["5462", "5573"], title: "Social Padel Clubs and Artisanal Coffee", sourceUrl: "https://athletechnews.com/the-rise-of-social-sports-clubs-padel-pickleball-and-premium-coffee/", snippet: "New multi-use sports venues prioritize social spaces to drive recurring revenue." },

  // --- BEAUTY ---
  { articleId: "9501", vertical: Vertical.Beauty, trendIds: ["5389"], title: "Aroma Wearable Tech Launch", sourceUrl: "https://www.fragrantica.com", snippet: "New wearable jewelry released that releases periodic bursts of signature scents." },
  { articleId: "9502", vertical: Vertical.Beauty, trendIds: ["5392"], title: "Neuroscience-Backed Perfume Research", sourceUrl: "https://www.beautytech.com", snippet: "Major fragrance house uses brainwave tracking to identify which scent notes correlate most highly with stress reduction and focus." },
  { articleId: "9503", vertical: Vertical.Beauty, trendIds: ["5558"], title: "The Rise of One-Step Serums", sourceUrl: "https://www.skincareexpert.com", snippet: "Brands are consolidating routines into single 'hero' serums to maximize convenience and conversion." },
  { articleId: "9600", vertical: Vertical.Beauty, trendIds: ["5563"], title: "Cafe-Integrated Beauty Concept Stores", sourceUrl: "https://www.beautytech.com/cafe-retail-beauty-overlap", snippet: "Beauty retailers are launching 'wellness cafes' inside clinics serving mood-boosting beverages." },
];
